# Site settings
title: QVXX Consulting
description: AI Solutions for London SMBs
url: "https://qvxx.ai"
baseurl: ""

# Build settings
markdown: kramdown

# Plugins
plugins:
  - jekyll-seo-tag

# Exclude files
exclude:
  - README.md
  - .gitignore
  - CNAME
  - _posts
  - scripts
